name: Vercel Preview Deployment

on:
  # Manual “Run workflow” button
  workflow_dispatch:
  # Auto on pushes to non-main branches
  push:
    branches-ignore:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      VERCEL_ORG_ID:    ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      VERCEL_TOKEN:     ${{ secrets.VERCEL_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel env (Preview)
        if: github.ref != 'refs/heads/main'
        run: vercel env pull .env.local --environment=preview --token=$VERCEL_TOKEN

      - name: Pull Vercel env (Production)
        if: github.ref == 'refs/heads/main'
        run: vercel env pull .env.local --environment=production --token=$VERCEL_TOKEN

      - name: Build project
        run: vercel build --token=$VERCEL_TOKEN

      - name: Deploy to Vercel
        run: vercel deploy --prebuilt --token=$VERCEL_TOKEN
