# .github/workflows/vercel-preview.yml
name: Vercel Preview Deployment

on:
  # Manual trigger from the Actions tab
  workflow_dispatch:

  # Push to any branch **except** main
  push:
    branches-ignore:
      - main

# Cancel any in-progress run for the same branch/PR
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  VERCEL_ORG_ID:     ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  VERCEL_TOKEN:      ${{ secrets.VERCEL_TOKEN }}

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Vercel CLI
        run: npm i -g vercel@latest

      - name: Pull Vercel config & env (preview)
        run: |
          vercel pull --yes --environment=preview --token=$VERCEL_TOKEN
          vercel env pull .env.local --environment=preview --token=$VERCEL_TOKEN

      - name: Build
        run: vercel build --token=$VERCEL_TOKEN

      - name: Deploy Preview
        run: |
          vercel deploy --prebuilt --token=$VERCEL_TOKEN